### ISSUE TITLE
more clear week3 homework Readme file

### ISSUE THREAD

**Issue by sima-milli** [HackYourFuture/Node.js#257]
in my opinion Readme file in week3 for the homework is not clear, maybe it is better to show how the todo should be stored in the json file i.e 
{
    "id": "7f3abae4-0985-408b-8daa-b51582144e1b",
    "task": "something",
    "done": false
  }
the "id" is generated by uuid and the "task" value is taken from Postman request body. 

Maybe that helps make things a bit clearer.

**Comment by gijscor** [comment]
@J05J4 @GeorgeSapkin would you agree?
