### ISSUE TITLE
Example HYF Planning Issue

### ISSUE THREAD

**Issue by remarcmij** [HackYourFuture/Node.js#343]
## Class 20 - Node.js

> Note: `$`-signs to be replaced with`@`-signs to enable GitHub mentions.

Generated with this tool: https://github.com/remarcmij/hyf-plan
#### Teachers
  - [x] $josja Josja
  - [x] $yash-kapila

### Week 1 - 12/05/2019

- [x] Lecture delivered
- [ ] Recordings uploaded

#### Homework reviewed

  - [ ] $Akif2709 #350 
  - [ ] $alaashhadat #346 
  - [ ] $eneserdek #349 
  - [ ] $ghifo
  - [ ] $mohammadnaefaldarwesh
  - [ ] $Muhannad1989 #347 
  - [ ] $Nadoshka
  - [ ] $OrhanGoc
  - [x] $RamazanInce #345 
  - [ ] $sigma21
  - [ ] $WadeeaKiwan #348 

#### Homework approved

  - [ ] $Akif2709
  - [ ] $alaashhadat
  - [ ] $eneserdek
  - [ ] $ghifo
  - [ ] $mohammadnaefaldarwesh
  - [ ] $Muhannad1989
  - [ ] $Nadoshka
  - [ ] $OrhanGoc
  - [ ] $RamazanInce
  - [ ] $sigma21
  - [ ] $WadeeaKiwan

### Week 2 - 19/05/2019

- [ ] Lecture delivered
- [ ] Recordings uploaded

#### Homework reviewed

  - [ ] $Akif2709
  - [ ] $alaashhadat
  - [ ] $eneserdek
  - [ ] $ghifo
  - [ ] $mohammadnaefaldarwesh
  - [ ] $Muhannad1989
  - [ ] $Nadoshka
  - [ ] $OrhanGoc
  - [ ] $RamazanInce
  - [ ] $sigma21
  - [ ] $WadeeaKiwan

#### Homework approved

  - [ ] $Akif2709
  - [ ] $alaashhadat
  - [ ] $eneserdek
  - [ ] $ghifo
  - [ ] $mohammadnaefaldarwesh
  - [ ] $Muhannad1989
  - [ ] $Nadoshka
  - [ ] $OrhanGoc
  - [ ] $RamazanInce
  - [ ] $sigma21
  - [ ] $WadeeaKiwan

### Week 3 - 26/05/2019

- [ ] Lecture delivered
- [ ] Recordings uploaded

#### Homework reviewed

  - [ ] $Akif2709
  - [ ] $alaashhadat
  - [ ] $eneserdek
  - [ ] $ghifo
  - [ ] $mohammadnaefaldarwesh
  - [ ] $Muhannad1989
  - [ ] $Nadoshka
  - [ ] $OrhanGoc
  - [ ] $RamazanInce
  - [ ] $sigma21
  - [ ] $WadeeaKiwan

#### Homework approved

  - [ ] $Akif2709
  - [ ] $alaashhadat
  - [ ] $eneserdek
  - [ ] $ghifo
  - [ ] $mohammadnaefaldarwesh
  - [ ] $Muhannad1989
  - [ ] $Nadoshka
  - [ ] $OrhanGoc
  - [ ] $RamazanInce
  - [ ] $sigma21
  - [ ] $WadeeaKiwan

**Comment by robvk** [comment]
Cleaning up
