### ISSUE TITLE
Irrelevant video

### ISSUE THREAD

**Issue by anis790615** [HackYourFuture/Node.js#541]
The video linked in section 1. Making use of other APIs, titled "The Many Meanings of Event-Driven Architecture • Martin Fowler", has nothing to do with the topic that the section claims to be talking about. It is not about APIs and it's not about microservices. The word microservices was pronounced twice on the minute 48, and it is out of the context of APIs. The video is a bit complex and long, and even if useful, not in within the scope, of node.js, or even APIs.

**Comment by NoerGitKat** [comment]
Got it! Thanks for mentioning it @anis790615 !
