### ISSUE TITLE
Wrong numbering of a header

### ISSUE THREAD

**Issue by SergPerep** [HackYourFuture/Node.js#575]
[«4.1 Adding a POST request»](https://github.com/HackYourFuture/Node.js/blob/master/week1/MAKEME.md#41-adding-a-post-request) should be named «5.1 Adding a POST request» since it is the subtitle of [5. PROJECT: HackYourTemperature I](https://github.com/HackYourFuture/Node.js/blob/master/week1/MAKEME.md#5-project-hackyourtemperature-i).

**Comment by robvk** [comment]
Fixed, thanks!
