### ISSUE TITLE
classXX is confusing it should be cohortXX

### ISSUE THREAD

**Issue by AJasem** [HackYourFuture/Node.js#622]
i think the classXX should be now cohortXX because it is confusing for allot of the trainee
Create a [fork](https://help.github.com/en/articles/fork-a-repo) of the assignments module repository. For Node.js, the assignments module repository is https://www.github.com/HackYourAssignment/Node.js-classXX where XX is your class number. You do this by using the fork option on the top right

**Comment by stasel** [comment]
Yes, that is correct. Thank you for pointing this out. 
It is now fixed
